table titles
	lineageTag: 477797f8-d3b6-45a9-b27e-957eedd49d9c

	column type
		dataType: string
		lineageTag: f800210f-1139-4c62-ac37-a47984d72142
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column language
		dataType: string
		lineageTag: 87ba36e6-65c4-4f38-9dfe-3ff9a648c95c
		summarizeBy: none
		sourceColumn: language

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 65f56625-fc27-40c3-a399-9a9b29fe80a3
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 90257522-2b7d-47b4-8479-03ff6fabb096
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 2135d945-0b00-4950-8c51-e998c1eb655e
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	partition titles = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/t4d-gmbh/powerbi-example-surfspots/main/data/titles.csv"),[Delimiter=";", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"type", type text}, {"language", type text}, {"name", type text}, {"title", type text}, {"description", type text}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

