#!/bin/sh

# This Git Hook runs the script hide_visual_filters.py

remote="$1"
url="$2"

commit_msg="Git Hook (pre-push): Apply scripts/*.py to pbir files"


# Check if commit already exists
if git log -1 --pretty=%B | grep -q "$commit_msg"
then

  echo >&2 "Commit already exists"
  exit 0
  
else

  # Stath local changes on pbir files
  git stash push pbir/
  
  # Execute all python scripts in the scripts/folder
  SCRIPTS="scripts/*.py"
  for s in $SCRIPTS
  do
    python "$s"
  done

  # Check if some files were changed
  if git status | grep -q "nothing to commit"
  then
    git stash apply
	echo >&2 "Seems that noting was changed"
	exit 0
  else
    git add *
    git commit -m "$commit_msg"
	git stash apply
	echo >&2 "Check last commit [ git diff HEAD^ HEAD ] and run [ git push ] again if everything is OK."
	exit 1
  fi

fi

